import type { NutritionRecipe } from "./types.js";

export const NUTRITION_RECIPES: NutritionRecipe[] = [
  {
    id: "veg-omelet",
    title: "Овощной омлет",
    summary: "Лёгкий белковый завтрак с овощами",
    meal: "breakfast",
    method: "stew",
    prepMinutes: 5,
    cookMinutes: 12,
    caloriesPerServing: 220,
    servings: 1,
    ingredients: [
      { id: "egg", amount: "2 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "bell_pepper", amount: "½ шт." },
      { id: "spinach", amount: "горсть", optional: true },
      { id: "olive_oil", amount: "1 ч. л.", optional: true },
    ],
    steps: [
      "Нарежьте помидор и перец небольшими кубиками.",
      "Слегка обжарьте овощи на сухой сковороде с каплей масла 2–3 минуты.",
      "Взбейте яйца, вылейте на овощи, добавьте шпинат.",
      "Накройте крышкой и готовьте на слабом огне 6–8 минут до схватывания.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "oat-apple",
    title: "Овсянка с яблоком",
    summary: "Сытный ПП-завтрак за 10 минут",
    meal: "breakfast",
    method: "boil",
    prepMinutes: 3,
    cookMinutes: 8,
    caloriesPerServing: 280,
    servings: 1,
    ingredients: [
      { id: "oatmeal", amount: "50 г" },
      { id: "apple", amount: "1 шт." },
      { id: "milk", amount: "200 мл", optional: true },
      { id: "honey", amount: "1 ч. л.", optional: true },
      { id: "nuts", amount: "10 г", optional: true },
    ],
    steps: [
      "Доведите молоко или воду до кипения, засыпьте овсянку.",
      "Варите 5–7 минут, помешивая.",
      "Яблоко нарежьте кубиками, добавьте в кашу.",
      "Подавайте с мёдом и орехами по желанию.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "protein-salad",
    title: "Белковый салат с йогуртовой заправкой",
    summary: "Салат по формуле: белок + овощи + лёгкая заправка",
    meal: "lunch",
    method: "mix",
    prepMinutes: 10,
    cookMinutes: 0,
    caloriesPerServing: 250,
    servings: 1,
    ingredients: [
      { id: "chicken_breast", amount: "150 г" },
      { id: "cucumber", amount: "1 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "lettuce", amount: "2 горсти" },
      { id: "yogurt", amount: "2 ст. л." },
      { id: "lemon", amount: "сок ½ шт.", optional: true },
    ],
    steps: [
      "Отварите или запеките куриную грудку, нарежьте ломтиками.",
      "Нарежьте овощи, смешайте с листьями салата.",
      "Смешайте йогурт с лимонным соком и щепоткой соли.",
      "Полейте салат заправкой, добавьте курицу.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "chicken-veg-oven",
    title: "Куриная грудка с овощами в духовке",
    summary: "Запечённое блюдо на один противень",
    meal: "dinner",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 35,
    caloriesPerServing: 320,
    servings: 2,
    ingredients: [
      { id: "chicken_breast", amount: "300 г" },
      { id: "zucchini", amount: "1 шт." },
      { id: "bell_pepper", amount: "1 шт." },
      { id: "broccoli", amount: "200 г" },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
      { id: "garlic", amount: "2 зубчика", optional: true },
    ],
    steps: [
      "Разогрейте духовку до 190 °C.",
      "Нарежьте курицу и овощи крупными кусками.",
      "Смешайте с маслом, солью, перцем и чесноком.",
      "Выложите на противень, запекайте 30–35 минут.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "buckwheat-turkey",
    title: "Гречка с индейкой",
    summary: "Классическое сбалансированное блюдо",
    meal: "lunch",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 25,
    caloriesPerServing: 380,
    servings: 2,
    ingredients: [
      { id: "buckwheat", amount: "120 г" },
      { id: "turkey", amount: "300 г" },
      { id: "onion", amount: "1 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Отварите гречку до готовности.",
      "Нарежьте индейку кубиками, обжарьте с луком и морковью 5 минут.",
      "Добавьте немного воды, тушите под крышкой 15 минут.",
      "Подавайте индейку с гречкой.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "buckwheat-chicken",
    title: "Гречка с курицей",
    summary: "Сбалансированный обед из доступных продуктов",
    meal: "lunch",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 25,
    caloriesPerServing: 390,
    servings: 2,
    ingredients: [
      { id: "buckwheat", amount: "120 г" },
      { id: "chicken_breast", amount: "300 г" },
      { id: "onion", amount: "1 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Отварите гречку до готовности.",
      "Нарежьте курицу кубиками, обжарьте с луком и морковью 5 минут.",
      "Добавьте немного воды, тушите под крышкой 15 минут.",
      "Подавайте курицу с гречкой.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "cottage-cheese-bake",
    title: "Творожная запеканка",
    summary: "Нежный ПП-десерт или завтрак",
    meal: "breakfast",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 30,
    caloriesPerServing: 240,
    servings: 3,
    ingredients: [
      { id: "cottage_cheese", amount: "400 г" },
      { id: "egg", amount: "2 шт." },
      { id: "oatmeal", amount: "3 ст. л." },
      { id: "honey", amount: "1 ст. л.", optional: true },
      { id: "apple", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Разомните творог вилкой, добавьте яйца и овсянку.",
      "Яблоко натрите, смешайте с творогом.",
      "Выложите в форму, запекайте при 180 °C 25–30 минут.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "baked-fish-broccoli",
    title: "Запечённая рыба с брокколи",
    summary: "Лёгкий ужин с омега-3",
    meal: "dinner",
    method: "bake",
    prepMinutes: 8,
    cookMinutes: 20,
    caloriesPerServing: 290,
    servings: 1,
    ingredients: [
      { id: "salmon", amount: "180 г" },
      { id: "broccoli", amount: "200 г" },
      { id: "lemon", amount: "½ шт.", optional: true },
      { id: "olive_oil", amount: "1 ч. л." },
      { id: "garlic", amount: "1 зубчик", optional: true },
    ],
    steps: [
      "Разогрейте духовку до 200 °C.",
      "Выложите рыбу и брокколи на противень.",
      "Сбрызните маслом и лимоном, посолите.",
      "Запекайте 18–20 минут.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "veg-ragout",
    title: "Овощное рагу",
    summary: "Тушёные овощи без лишнего жира",
    meal: "dinner",
    method: "stew",
    prepMinutes: 12,
    cookMinutes: 25,
    caloriesPerServing: 180,
    servings: 2,
    ingredients: [
      { id: "zucchini", amount: "1 шт." },
      { id: "eggplant", amount: "1 шт." },
      { id: "tomato", amount: "2 шт." },
      { id: "bell_pepper", amount: "1 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "tomato_paste", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Нарежьте все овощи кубиками.",
      "Обжарьте лук, добавьте овощи и томатную пасту.",
      "Тушите под крышкой 20–25 минут на слабом огне.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "kefir-okroshka",
    title: "Лёгкая окрошка на кефире",
    summary: "Освежающий обед без готовки на плите",
    meal: "lunch",
    method: "mix",
    prepMinutes: 15,
    cookMinutes: 0,
    caloriesPerServing: 200,
    servings: 2,
    ingredients: [
      { id: "kefir", amount: "500 мл" },
      { id: "cucumber", amount: "2 шт." },
      { id: "radish", amount: "5 шт." },
      { id: "egg", amount: "2 шт." },
      { id: "herbs", amount: "пучок", optional: true },
      { id: "potato", amount: "2 шт.", optional: true },
    ],
    steps: [
      "Отварите яйца и картофель (если используете), остудите.",
      "Нарежьте овощи и яйца мелким кубиком.",
      "Залейте кефиром, добавьте зелень и соль.",
      "Подавайте охлаждённой.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "zucchini-fritters",
    title: "Кабачковые оладьи в духовке",
    summary: "ПП-оладьи без жарки во фритюре",
    meal: "snack",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 25,
    caloriesPerServing: 160,
    servings: 2,
    ingredients: [
      { id: "zucchini", amount: "2 шт." },
      { id: "egg", amount: "1 шт." },
      { id: "oatmeal", amount: "3 ст. л." },
      { id: "garlic", amount: "1 зубчик", optional: true },
      { id: "yogurt", amount: "для подачи", optional: true },
    ],
    steps: [
      "Натрите кабачки, отожмите лишнюю жидкость.",
      "Смешайте с яйцом, овсянкой и чесноком.",
      "Выложите ложкой на противень, запекайте при 190 °C 20–25 минут.",
      "Подавайте с йогуртом.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "lentil-soup",
    title: "Суп из чечевицы с овощами",
    summary: "Сытный суп без мяса",
    meal: "lunch",
    method: "boil",
    prepMinutes: 10,
    cookMinutes: 30,
    caloriesPerServing: 260,
    servings: 3,
    ingredients: [
      { id: "lentils", amount: "150 г" },
      { id: "carrot", amount: "1 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "potato", amount: "2 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Обжарьте лук и морковь на капле масла.",
      "Добавьте чечевицу, нарезанные овощи и 1 л воды.",
      "Варите 25–30 минут до мягкости чечевицы.",
    ],
    tags: ["pp"],
  },
  {
    id: "rice-cottage-chicken",
    title: "Рис с курицей и творожным соусом",
    summary: "Сытный обед из простых продуктов",
    meal: "lunch",
    method: "stew",
    prepMinutes: 10,
    cookMinutes: 25,
    caloriesPerServing: 400,
    servings: 2,
    ingredients: [
      { id: "rice", amount: "150 г" },
      { id: "chicken_breast", amount: "250 г" },
      { id: "cucumber", amount: "1 шт." },
      { id: "cottage_cheese", amount: "120 г" },
      { id: "herbs", amount: "по вкусу", optional: true },
    ],
    steps: [
      "Отварите рис до готовности.",
      "Курицу нарежьте полосками и обжарьте на сухой сковороде 8–10 минут.",
      "Огурец нарежьте, смешайте с творогом до кремовой консистенции.",
      "Подавайте рис с курицей, сверху — творожный соус с огурцом.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "rice-chicken-bowl",
    title: "Рис с курицей и овощами",
    summary: "Bowl на каждый день",
    meal: "lunch",
    method: "stew",
    prepMinutes: 10,
    cookMinutes: 25,
    caloriesPerServing: 410,
    servings: 2,
    ingredients: [
      { id: "rice", amount: "150 г" },
      { id: "chicken_breast", amount: "250 г" },
      { id: "bell_pepper", amount: "1 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "soy_sauce", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Отварите рис.",
      "Нарежьте курицу и овощи, обжарьте на сухой сковороде 8–10 минут.",
      "Добавьте соевый соус, подавайте с рисом.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "tuna-salad",
    title: "Салат с тунцом",
    summary: "Быстрый обед за 10 минут",
    meal: "lunch",
    method: "mix",
    prepMinutes: 8,
    cookMinutes: 0,
    caloriesPerServing: 280,
    servings: 1,
    ingredients: [
      { id: "tuna_canned", amount: "1 банка" },
      { id: "cucumber", amount: "1 шт." },
      { id: "corn", amount: "3 ст. л.", optional: true },
      { id: "yogurt", amount: "2 ст. л." },
      { id: "lettuce", amount: "1 горсть" },
    ],
    steps: [
      "Слейте жидкость из тунца.",
      "Нарежьте огурец, смешайте с тунцом и кукурузой.",
      "Заправьте йогуртом, выложите на салат.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "pasta-veg",
    title: "Паста с овощами",
    summary: "Цельнозерновая паста с соусом из овощей",
    meal: "dinner",
    method: "boil",
    prepMinutes: 10,
    cookMinutes: 20,
    caloriesPerServing: 350,
    servings: 2,
    ingredients: [
      { id: "pasta", amount: "180 г" },
      { id: "tomato", amount: "3 шт." },
      { id: "zucchini", amount: "1 шт." },
      { id: "garlic", amount: "2 зубчика" },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
      { id: "herbs", amount: "по вкусу", optional: true },
    ],
    steps: [
      "Отварите пасту al dente.",
      "Обжарьте чеснок, добавьте нарезанные овощи.",
      "Тушите 10 минут, смешайте с пастой и зеленью.",
    ],
    tags: ["pp"],
  },
  {
    id: "shrimp-veg",
    title: "Креветки с овощами",
    summary: "Быстрый белковый ужин",
    meal: "dinner",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 12,
    caloriesPerServing: 260,
    servings: 1,
    ingredients: [
      { id: "shrimp", amount: "200 г" },
      { id: "bell_pepper", amount: "1 шт." },
      { id: "zucchini", amount: "1 шт." },
      { id: "garlic", amount: "1 зубчик" },
      { id: "lemon", amount: "½ шт.", optional: true },
    ],
    steps: [
      "Обжарьте креветки с чесноком 2–3 минуты.",
      "Добавьте нарезанные овощи, готовьте ещё 5–7 минут.",
      "Сбрызните лимоном перед подачей.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "quinoa-bowl",
    title: "Киноа с овощами и фетой",
    summary: "Сбалансированный обед",
    meal: "lunch",
    method: "boil",
    prepMinutes: 10,
    cookMinutes: 20,
    caloriesPerServing: 340,
    servings: 2,
    ingredients: [
      { id: "quinoa", amount: "120 г" },
      { id: "cucumber", amount: "1 шт." },
      { id: "tomato", amount: "2 шт." },
      { id: "feta", amount: "50 г" },
      { id: "olive_oil", amount: "1 ст. л.", optional: true },
      { id: "lemon", amount: "½ шт.", optional: true },
    ],
    steps: [
      "Отварите киноа по инструкции на упаковке.",
      "Нарежьте овощи, смешайте с киноа.",
      "Добавьте фету, масло и лимонный сок.",
    ],
    tags: ["pp"],
  },
  {
    id: "beef-stew-veg",
    title: "Говядина тушёная с овощами",
    summary: "Сытное блюдо на ужин",
    meal: "dinner",
    method: "stew",
    prepMinutes: 12,
    cookMinutes: 50,
    caloriesPerServing: 380,
    servings: 2,
    ingredients: [
      { id: "beef_lean", amount: "300 г" },
      { id: "potato", amount: "2 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "tomato_paste", amount: "1 ст. л." },
    ],
    steps: [
      "Нарежьте говядину кубиками, обжарьте без масла 5 минут.",
      "Добавьте лук, морковь, томатную пасту и воду.",
      "Тушите 40 минут, за 15 минут до конца добавьте картофель.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "chickpea-curry",
    title: "Нут с овощами",
    summary: "Растительный белок и клетчатка",
    meal: "lunch",
    method: "stew",
    prepMinutes: 10,
    cookMinutes: 25,
    caloriesPerServing: 310,
    servings: 2,
    ingredients: [
      { id: "chickpeas", amount: "250 г" },
      { id: "tomato", amount: "2 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "spinach", amount: "горсть", optional: true },
      { id: "ginger", amount: "1 ч. л.", optional: true },
    ],
    steps: [
      "Обжарьте лук, добавьте нут и нарезанные томаты.",
      "Тушите 15 минут, в конце добавьте шпинат.",
    ],
    tags: ["pp"],
  },
  {
    id: "egg-avocado-toast",
    title: "Яйцо пашот с овощами",
    summary: "Плотный завтрак без сахара",
    meal: "breakfast",
    method: "boil",
    prepMinutes: 5,
    cookMinutes: 10,
    caloriesPerServing: 230,
    servings: 1,
    ingredients: [
      { id: "egg", amount: "2 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "cucumber", amount: "½ шт." },
      { id: "bread_whole", amount: "1 ломтик", optional: true },
      { id: "herbs", amount: "по вкусу", optional: true },
    ],
    steps: [
      "Сварите яйца всмятку или пашот 6–7 минут.",
      "Нарежьте овощи, подавайте с яйцами и зеленью.",
      "Можно выложить на цельнозерновой хлеб.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "cottage-snack",
    title: "Творог с ягодным яблоком",
    summary: "Быстрый перекус",
    meal: "snack",
    method: "mix",
    prepMinutes: 3,
    cookMinutes: 0,
    caloriesPerServing: 180,
    servings: 1,
    ingredients: [
      { id: "cottage_cheese", amount: "150 г" },
      { id: "apple", amount: "½ шт." },
      { id: "honey", amount: "1 ч. л.", optional: true },
      { id: "nuts", amount: "5 г", optional: true },
    ],
    steps: [
      "Нарежьте яблоко кубиками.",
      "Смешайте с творогом, добавьте мёд и орехи по желанию.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "mushroom-omelet",
    title: "Омлет с грибами",
    summary: "Сытный завтрак с шампиньонами",
    meal: "breakfast",
    method: "stew",
    prepMinutes: 5,
    cookMinutes: 12,
    caloriesPerServing: 210,
    servings: 1,
    ingredients: [
      { id: "egg", amount: "2 шт." },
      { id: "mushroom", amount: "150 г" },
      { id: "onion", amount: "½ шт." },
      { id: "herbs", amount: "по вкусу", optional: true },
    ],
    steps: [
      "Нарежьте грибы и лук, обжарьте на сухой сковороде 4–5 минут.",
      "Взбейте яйца, вылейте на грибы.",
      "Готовьте под крышкой на слабом огне 6–8 минут.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "banana-oat",
    title: "Овсянка с бананом",
    summary: "Быстрый завтрак без сахара",
    meal: "breakfast",
    method: "boil",
    prepMinutes: 3,
    cookMinutes: 8,
    caloriesPerServing: 290,
    servings: 1,
    ingredients: [
      { id: "oatmeal", amount: "50 г" },
      { id: "banana", amount: "1 шт." },
      { id: "milk", amount: "200 мл", optional: true },
      { id: "flax_seeds", amount: "1 ч. л.", optional: true },
    ],
    steps: [
      "Доведите молоко или воду до кипения, засыпьте овсянку.",
      "Варите 5–7 минут, помешивая.",
      "Банан нарежьте кружочками, добавьте в кашу.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "cottage-banana",
    title: "Творог с бананом",
    summary: "Простой перекус за 3 минуты",
    meal: "snack",
    method: "mix",
    prepMinutes: 3,
    cookMinutes: 0,
    caloriesPerServing: 190,
    servings: 1,
    ingredients: [
      { id: "cottage_cheese", amount: "150 г" },
      { id: "banana", amount: "1 шт." },
      { id: "honey", amount: "1 ч. л.", optional: true },
    ],
    steps: [
      "Банан нарежьте кружочками.",
      "Смешайте с творогом, по желанию добавьте мёд.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "avocado-egg-salad",
    title: "Салат с авокадо и яйцом",
    summary: "Свежий салат с полезными жирами",
    meal: "lunch",
    method: "mix",
    prepMinutes: 10,
    cookMinutes: 8,
    caloriesPerServing: 320,
    servings: 1,
    ingredients: [
      { id: "avocado", amount: "1 шт." },
      { id: "egg", amount: "2 шт." },
      { id: "cucumber", amount: "1 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "lemon", amount: "сок ½ шт.", optional: true },
    ],
    steps: [
      "Сварите яйца вкрутую 8–9 минут, остудите и нарежьте.",
      "Авокадо, огурец и помидор нарежьте кубиками.",
      "Смешайте, посолите, сбрызните лимоном по желанию.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "cauliflower-bake",
    title: "Запечённая цветная капуста с сыром",
    summary: "Лёгкий ужин из духовки",
    meal: "dinner",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 25,
    caloriesPerServing: 240,
    servings: 2,
    ingredients: [
      { id: "cauliflower", amount: "400 г" },
      { id: "egg", amount: "1 шт." },
      { id: "cheese", amount: "50 г" },
      { id: "garlic", amount: "1 зубчик", optional: true },
    ],
    steps: [
      "Разогрейте духовку до 190 °C.",
      "Капусту разберите на соцветия, отварите 5 минут.",
      "Смешайте с яйцом и тертым сыром, выложите в форму.",
      "Запекайте 20–25 минут до золотистой корочки.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "chicken-cabbage",
    title: "Курица с капустой",
    summary: "Сытное блюдо в одной сковороде",
    meal: "dinner",
    method: "stew",
    prepMinutes: 10,
    cookMinutes: 30,
    caloriesPerServing: 310,
    servings: 2,
    ingredients: [
      { id: "chicken_breast", amount: "300 г" },
      { id: "cabbage", amount: "300 г" },
      { id: "carrot", amount: "1 шт." },
      { id: "onion", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Нарежьте курицу полосками, обжарьте на сухой сковороде 5 минут.",
      "Добавьте нашинкованную капусту, морковь и лук.",
      "Тушите под крышкой 20–25 минут, посолите по вкусу.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "cod-potato",
    title: "Треска с картофелем",
    summary: "Классический ужин из рыбы и овощей",
    meal: "dinner",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 30,
    caloriesPerServing: 300,
    servings: 2,
    ingredients: [
      { id: "cod", amount: "300 г" },
      { id: "potato", amount: "2 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "onion", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Разогрейте духовку до 190 °C.",
      "Картофель и морковь нарежьте кружочками, выложите на противень.",
      "Сверху положите филе трески, посолите.",
      "Запекайте 25–30 минут до готовности рыбы.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "bean-tomato",
    title: "Фасоль с томатами",
    summary: "Растительный белок без мяса",
    meal: "lunch",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 20,
    caloriesPerServing: 280,
    servings: 2,
    ingredients: [
      { id: "beans", amount: "250 г" },
      { id: "tomato", amount: "2 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "garlic", amount: "1 зубчик", optional: true },
    ],
    steps: [
      "Обжарьте лук и чеснок на сухой сковороде.",
      "Добавьте нарезанные томаты и фасоль.",
      "Тушите 15–20 минут до мягкости.",
    ],
    tags: ["pp"],
  },
  {
    id: "tofu-pepper",
    title: "Тофу с овощами",
    summary: "Лёгкий ужин на сковороде",
    meal: "dinner",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 15,
    caloriesPerServing: 260,
    servings: 2,
    ingredients: [
      { id: "tofu", amount: "250 г" },
      { id: "bell_pepper", amount: "1 шт." },
      { id: "zucchini", amount: "1 шт." },
      { id: "soy_sauce", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Тофу нарежьте кубиками, обжарьте 3–4 минуты.",
      "Добавьте нарезанные перец и кабачок.",
      "Готовьте ещё 8–10 минут, в конце добавьте соевый соус.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "pumpkin-cottage",
    title: "Тыквенная запеканка с творогом",
    summary: "Нежный завтрак или перекус",
    meal: "breakfast",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 35,
    caloriesPerServing: 250,
    servings: 2,
    ingredients: [
      { id: "pumpkin", amount: "300 г" },
      { id: "cottage_cheese", amount: "200 г" },
      { id: "egg", amount: "1 шт." },
      { id: "honey", amount: "1 ч. л.", optional: true },
    ],
    steps: [
      "Тыкву натрите или нарежьте кубиками.",
      "Смешайте с творогом и яйцом.",
      "Выложите в форму, запекайте при 180 °C 30–35 минут.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "turkey-salad",
    title: "Салат с индейкой",
    summary: "Быстрый обед без готовки на плите",
    meal: "lunch",
    method: "mix",
    prepMinutes: 10,
    cookMinutes: 15,
    caloriesPerServing: 270,
    servings: 1,
    ingredients: [
      { id: "turkey", amount: "150 г" },
      { id: "cucumber", amount: "1 шт." },
      { id: "tomato", amount: "1 шт." },
      { id: "lettuce", amount: "1 горсть", optional: true },
    ],
    steps: [
      "Отварите или запеките индейку, нарежьте ломтиками.",
      "Овощи нарежьте, смешайте с мясом.",
      "Посолите, подавайте сразу.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "egg-fried-rice",
    title: "Рис с яйцом и овощами",
    summary: "Простой bowl на обед",
    meal: "lunch",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 20,
    caloriesPerServing: 380,
    servings: 2,
    ingredients: [
      { id: "rice", amount: "150 г" },
      { id: "egg", amount: "2 шт." },
      { id: "carrot", amount: "1 шт." },
      { id: "peas", amount: "100 г" },
      { id: "soy_sauce", amount: "1 ст. л.", optional: true },
    ],
    steps: [
      "Отварите рис до готовности.",
      "Яйца взбейте и обжарьте на сухой сковороде, разомните вилкой.",
      "Добавьте нарезанную морковь и горошек, готовьте 5 минут.",
      "Смешайте с рисом, по желанию добавьте соевый соус.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "mushroom-potato",
    title: "Грибы с картофелем",
    summary: "Домашнее тушёное блюдо",
    meal: "dinner",
    method: "stew",
    prepMinutes: 10,
    cookMinutes: 30,
    caloriesPerServing: 220,
    servings: 2,
    ingredients: [
      { id: "mushroom", amount: "250 г" },
      { id: "potato", amount: "3 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "carrot", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Картофель нарежьте кубиками, обжарьте с луком 5 минут.",
      "Добавьте грибы и морковь.",
      "Тушите под крышкой 20–25 минут, добавив немного воды.",
    ],
    tags: ["pp"],
  },
  {
    id: "pear-cottage",
    title: "Творог с грушей",
    summary: "Лёгкий десертный перекус",
    meal: "snack",
    method: "mix",
    prepMinutes: 3,
    cookMinutes: 0,
    caloriesPerServing: 175,
    servings: 1,
    ingredients: [
      { id: "cottage_cheese", amount: "150 г" },
      { id: "pear", amount: "1 шт." },
      { id: "nuts", amount: "5 г", optional: true },
    ],
    steps: [
      "Грушу нарежьте кубиками.",
      "Смешайте с творогом, по желанию посыпьте орехами.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "sweet-potato-chicken",
    title: "Курица с бататом",
    summary: "Сытный ужин с медленными углеводами",
    meal: "dinner",
    method: "bake",
    prepMinutes: 10,
    cookMinutes: 35,
    caloriesPerServing: 350,
    servings: 2,
    ingredients: [
      { id: "sweet_potato", amount: "2 шт." },
      { id: "chicken_breast", amount: "300 г" },
      { id: "bell_pepper", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Разогрейте духовку до 190 °C.",
      "Батат и курицу нарежьте крупными кусками.",
      "Выложите на противень, посолите.",
      "Запекайте 30–35 минут до готовности.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "lentil-carrot-soup",
    title: "Суп из чечевицы с морковью",
    summary: "Простой суп на обед",
    meal: "lunch",
    method: "boil",
    prepMinutes: 8,
    cookMinutes: 25,
    caloriesPerServing: 240,
    servings: 2,
    ingredients: [
      { id: "lentils", amount: "120 г" },
      { id: "carrot", amount: "1 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "potato", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Обжарьте лук и морковь на сухой сковороде.",
      "Добавьте чечевицу, картофель и 800 мл воды.",
      "Варите 20–25 минут до мягкости чечевицы.",
    ],
    tags: ["pp"],
  },
  {
    id: "pasta-tuna",
    title: "Паста с тунцом",
    summary: "Быстрый ужин за 20 минут",
    meal: "dinner",
    method: "boil",
    prepMinutes: 8,
    cookMinutes: 15,
    caloriesPerServing: 390,
    servings: 2,
    ingredients: [
      { id: "pasta", amount: "180 г" },
      { id: "tuna_canned", amount: "1 банка" },
      { id: "tomato", amount: "2 шт." },
      { id: "garlic", amount: "1 зубчик", optional: true },
    ],
    steps: [
      "Отварите пасту al dente.",
      "Томаты нарежьте, потушите с чесноком 5 минут.",
      "Добавьте тунец, смешайте с пастой.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "shrimp-rice",
    title: "Креветки с рисом",
    summary: "Лёгкий ужин с морепродуктами",
    meal: "dinner",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 20,
    caloriesPerServing: 340,
    servings: 2,
    ingredients: [
      { id: "shrimp", amount: "250 г" },
      { id: "rice", amount: "120 г" },
      { id: "garlic", amount: "1 зубчик", optional: true },
      { id: "lemon", amount: "½ шт.", optional: true },
    ],
    steps: [
      "Отварите рис.",
      "Креветки обжарьте с чесноком 3–4 минуты.",
      "Подавайте с рисом, сбрызните лимоном по желанию.",
    ],
    tags: ["pp", "high_protein", "quick"],
  },
  {
    id: "minced-zucchini",
    title: "Котлеты из куриного фарша с кабачком",
    summary: "Сочные ПП-котлеты в духовке",
    meal: "dinner",
    method: "bake",
    prepMinutes: 12,
    cookMinutes: 25,
    caloriesPerServing: 300,
    servings: 2,
    ingredients: [
      { id: "minced_chicken", amount: "400 г" },
      { id: "zucchini", amount: "1 шт." },
      { id: "onion", amount: "1 шт." },
      { id: "egg", amount: "1 шт.", optional: true },
    ],
    steps: [
      "Кабачок натрите, отожмите жидкость.",
      "Смешайте фарш с кабачком, луком и яйцом.",
      "Сформируйте котлеты, запекайте при 190 °C 20–25 минут.",
    ],
    tags: ["pp", "high_protein"],
  },
  {
    id: "beet-cottage",
    title: "Салат из свёклы с творогом",
    summary: "Освежающий салат без майонеза",
    meal: "lunch",
    method: "mix",
    prepMinutes: 10,
    cookMinutes: 40,
    caloriesPerServing: 200,
    servings: 2,
    ingredients: [
      { id: "beet", amount: "2 шт." },
      { id: "cottage_cheese", amount: "150 г" },
      { id: "garlic", amount: "1 зубчик", optional: true },
      { id: "sour_cream", amount: "2 ст. л.", optional: true },
    ],
    steps: [
      "Свёклу отварите до готовности, остудите и натрите.",
      "Смешайте с творогом, чесноком и сметаной по желанию.",
      "Подавайте охлаждённым.",
    ],
    tags: ["pp", "quick"],
  },
  {
    id: "bulgur-veg",
    title: "Булгур с овощами",
    summary: "Сытный гарнир или самостоятельное блюдо",
    meal: "lunch",
    method: "stew",
    prepMinutes: 8,
    cookMinutes: 20,
    caloriesPerServing: 290,
    servings: 2,
    ingredients: [
      { id: "bulgur", amount: "120 г" },
      { id: "zucchini", amount: "1 шт." },
      { id: "tomato", amount: "2 шт." },
      { id: "onion", amount: "1 шт." },
    ],
    steps: [
      "Обжарьте лук, добавьте нарезанные овощи.",
      "Залейте булгур водой в пропорции 1:2.",
      "Тушите под крышкой 15–18 минут до готовности.",
    ],
    tags: ["pp", "quick"],
  },
];

const RECIPE_BY_ID = new Map(NUTRITION_RECIPES.map((recipe) => [recipe.id, recipe]));

export function getNutritionRecipe(id: string): NutritionRecipe | undefined {
  return RECIPE_BY_ID.get(id);
}

export function isKnownNutritionRecipeId(id: string): boolean {
  return RECIPE_BY_ID.has(id);
}
